// <auto-generated />
using System;
using ECommerce.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.Domain.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "https://picsum.photos/seed/samsung/400/400",
                            Name = "Samsung"
                        },
                        new
                        {
                            Id = 2,
                            Image = "https://picsum.photos/seed/zara/400/400",
                            Name = "Zara"
                        },
                        new
                        {
                            Id = 3,
                            Image = "https://picsum.photos/seed/apple/400/400",
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 4,
                            Image = "https://picsum.photos/seed/nike/400/400",
                            Name = "Nike"
                        },
                        new
                        {
                            Id = 5,
                            Image = "https://picsum.photos/seed/nestle/400/400",
                            Name = "Nestle"
                        },
                        new
                        {
                            Id = 6,
                            Image = "https://picsum.photos/seed/ikea/400/400",
                            Name = "Ikea"
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("CartId", "ProductId")
                        .IsUnique();

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "https://picsum.photos/seed/electronics/400/400",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Image = "https://picsum.photos/seed/fashion/400/400",
                            Name = "Fashion"
                        },
                        new
                        {
                            Id = 3,
                            Image = "https://picsum.photos/seed/groceries/400/400",
                            Name = "Groceries"
                        },
                        new
                        {
                            Id = 4,
                            Image = "https://picsum.photos/seed/home/400/400",
                            Name = "Home"
                        },
                        new
                        {
                            Id = 5,
                            Image = "https://picsum.photos/seed/beauty/400/400",
                            Name = "Beauty"
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelivered")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentMethodType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ShippingCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShippingDetails")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ShippingPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalOrderPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageCover")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RatingsAverage")
                        .HasPrecision(3, 1)
                        .HasColumnType("decimal(3,1)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            CategoryId = 1,
                            Description = "A smartphone with a clear display and a full day of battery.",
                            ImageCover = "https://picsum.photos/seed/phone/600/600",
                            Price = 15000m,
                            RatingsAverage = 4.5m,
                            Title = "Samsung Galaxy Phone"
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            CategoryId = 1,
                            Description = "A lightweight laptop for study and everyday work.",
                            ImageCover = "https://picsum.photos/seed/laptop/600/600",
                            Price = 28000m,
                            RatingsAverage = 4.2m,
                            Title = "Samsung Laptop"
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 2,
                            CategoryId = 2,
                            Description = "A plain cotton shirt for daily wear.",
                            ImageCover = "https://picsum.photos/seed/shirt/600/600",
                            Price = 900m,
                            RatingsAverage = 4.0m,
                            Title = "Zara Cotton Shirt"
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 3,
                            CategoryId = 1,
                            Description = "A phone with a bright screen and a strong camera.",
                            ImageCover = "https://picsum.photos/seed/iphone/600/600",
                            Price = 42000m,
                            RatingsAverage = 4.8m,
                            Title = "Apple iPhone"
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 3,
                            CategoryId = 1,
                            Description = "A thin laptop for study and design work.",
                            ImageCover = "https://picsum.photos/seed/macbook/600/600",
                            Price = 55000m,
                            RatingsAverage = 4.7m,
                            Title = "Apple Laptop"
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 4,
                            CategoryId = 2,
                            Description = "Light shoes for daily walks and running.",
                            ImageCover = "https://picsum.photos/seed/shoes/600/600",
                            Price = 3200m,
                            RatingsAverage = 4.6m,
                            Title = "Nike Running Shoes"
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 2,
                            CategoryId = 2,
                            Description = "A light dress for warm days.",
                            ImageCover = "https://picsum.photos/seed/dress/600/600",
                            Price = 1400m,
                            RatingsAverage = 4.3m,
                            Title = "Zara Summer Dress"
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 5,
                            CategoryId = 3,
                            Description = "A one-liter box of milk.",
                            ImageCover = "https://picsum.photos/seed/milk/600/600",
                            Price = 35m,
                            RatingsAverage = 4.4m,
                            Title = "Nestle Milk Box"
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 5,
                            CategoryId = 3,
                            Description = "One kilogram of red apples.",
                            ImageCover = "https://picsum.photos/seed/apples/600/600",
                            Price = 45m,
                            RatingsAverage = 4.1m,
                            Title = "Fresh Red Apples"
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 6,
                            CategoryId = 4,
                            Description = "A non-stick pan for everyday cooking.",
                            ImageCover = "https://picsum.photos/seed/pan/600/600",
                            Price = 650m,
                            RatingsAverage = 4.2m,
                            Title = "Ikea Kitchen Pan"
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 6,
                            CategoryId = 4,
                            Description = "A small lamp for a study desk.",
                            ImageCover = "https://picsum.photos/seed/lamp/600/600",
                            Price = 480m,
                            RatingsAverage = 4.0m,
                            Title = "Ikea Desk Lamp"
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 2,
                            CategoryId = 5,
                            Description = "A light cream for everyday skincare.",
                            ImageCover = "https://picsum.photos/seed/cream/600/600",
                            Price = 220m,
                            RatingsAverage = 4.5m,
                            Title = "Daily Face Cream"
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            Url = "https://picsum.photos/seed/phone/600/600"
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 1,
                            Url = "https://picsum.photos/seed/phone-back/600/600"
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 2,
                            Url = "https://picsum.photos/seed/laptop/600/600"
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 3,
                            Url = "https://picsum.photos/seed/shirt/600/600"
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 4,
                            Url = "https://picsum.photos/seed/iphone/600/600"
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 5,
                            Url = "https://picsum.photos/seed/macbook/600/600"
                        },
                        new
                        {
                            Id = 7,
                            ProductId = 6,
                            Url = "https://picsum.photos/seed/shoes/600/600"
                        },
                        new
                        {
                            Id = 8,
                            ProductId = 7,
                            Url = "https://picsum.photos/seed/dress/600/600"
                        },
                        new
                        {
                            Id = 9,
                            ProductId = 8,
                            Url = "https://picsum.photos/seed/milk/600/600"
                        },
                        new
                        {
                            Id = 10,
                            ProductId = 9,
                            Url = "https://picsum.photos/seed/apples/600/600"
                        },
                        new
                        {
                            Id = 11,
                            ProductId = 10,
                            Url = "https://picsum.photos/seed/pan/600/600"
                        },
                        new
                        {
                            Id = 12,
                            ProductId = 11,
                            Url = "https://picsum.photos/seed/lamp/600/600"
                        },
                        new
                        {
                            Id = 13,
                            ProductId = 12,
                            Url = "https://picsum.photos/seed/cream/600/600"
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Phones"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Laptops"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Name = "Men"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "Women"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Name = "Fruit"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Name = "Dairy"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Name = "Kitchen"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 5,
                            Name = "Skincare"
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.WishlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("WishlistItems");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Cart", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.CartItem", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Order", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Product", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECommerce.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.ProductImage", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.SubCategory", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.WishlistItem", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECommerce.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Product", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
